### ISSUE TITLE
go 1.4  cannot work with gozmq4

### ISSUE THREAD

**Issue by DaviWei** [pebbe/zmq4#42]
Hi pebbe,

When I use go 1.3 to compile below code. it works fine. But if I use go 1.4 , it will report below error. when the program run .

```go
var ctx *zmq4.Context
var zmq_socket *zmq4.Socket

func init() {
	zmq_init()
}

func zmq_init() {
	fmt.Println("111111111")
	var err error

	ctx, err = zmq4.NewContext()
	if err != nil {
		fmt.Println("NewContext error!")
		panic("new contect error!")
	}

	zmq_socket, err = ctx.NewSocket(zmq4.PUB)
	if err != nil {
		fmt.Println("NewSocket error!")
		return
	}
	if zmq_socket.Bind("tcp://127.0.0.1:5557") != nil {
		fmt.Println("Bind error!")
		return
	}
}
```
========================================================
```
Exception 0xc0000096 0x0 0x0 0x905126
PC=0x905126
signal arrived during cgo execution

github.com/pebbe/zmq4._C2func_zmq_ctx_new(0x0, 0x0, 0x0)
        d:/gopath/src/github.com/pebbe/zmq4/:173 +0x57
github.com/pebbe/zmq4.init·1()
        d:/gopath/src/github.com/pebbe/zmq4/zmq4.go:91 +0x6c
github.com/pebbe/zmq4.init()
        d:/gopath/src/github.com/pebbe/zmq4/zmq4.go:1072 +0x2b9
main.init()
        D:/b/source/deploy/src/agent2/main.go:1173 +0x76

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1
eax     0x53756aa5
ebx     0x127f3f00
ecx     0x92a5c0
edx     0x127f3ec0
edi     0x140
esi     0x920be0
ebp     0x920fe0
esp     0x18feac
eip     0x905126
eflags  0x10203
cs      0x23
fs      0x53
gs      0x2b
```

**Comment by pebbe** [comment]
As far as I can tell, Exception 0xc0000096 means there is something wrong with Windows system files.

Did you compile ZeroMQ and zmq4 yourself, or did you download binary versions? In the second case, there could be a binary mismatch between ZeroMQ and zmq4. Try reinstalling from source.

**Comment by vrecan** [comment]
I'm currently using go 1.4.2 with zmq 4.0.5 on windows 7/8, 2008r2 and 2012r2 without any issues.

**Comment by aletheia7** [comment]
@vrecan, Do you receive the same exception if you move the zmq_init() out of the init()?

**Comment by pebbe** [comment]
Closing because of lack of response from OP.
