### ISSUE TITLE
Assertion failed: pfd.revents & POLLIN (signaler.cpp:226)

### ISSUE THREAD

**Issue by mengzhuo** [pebbe/zmq4#50]
I'm using zerorpc golang binding it's fine at beginning however when there are more than 10 clients
It will throw this error
```
2015/06/29 23:10:21 ZeroRPC socket closed
Assertion failed: pfd.revents & POLLIN (signaler.cpp:226)
SIGABRT: abort
PC=0x7ffbcf34ccc9
signal arrived during cgo execution

goroutine 152 [syscall, locked to thread]:
runtime.cgocall_errno(0x4035b0, 0xc2080b3cc0, 0x0)
        /home/meng/projects/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080b3c80 sp=0xc2080b3c58
github.com/pebbe/zmq4._C2func_zmq_msg_recv(0xc2080b3d00, 0x7ffb9c015aa0, 0x0, 0x0, 0x0, 0x0)
        /home/meng/projects/PQServer/goedge/src/github.com/pebbe/zmq4/:225 +0x55 fp=0xc2080b3cc0 sp=0xc2080b3c80
github.com/pebbe/zmq4.(*Socket).RecvBytes(0xc2080c3e30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/meng/projects/PQServer/goedge/src/github.com/pebbe/zmq4/zmq4.go:682 +0x2c5 fp=0xc2080b3dd8 sp=0xc2080b3cc0
github.com/pebbe/zmq4.(*Socket).RecvMessageBytes(0xc2080c3e30, 0x0, 0xf032b0, 0x0, 0x0, 0x0, 0x0)
        /home/meng/projects/PQServer/goedge/src/github.com/pebbe/zmq4/utils.go:118 +0xc0 fp=0xc2080b3e60 sp=0xc2080b3dd8
github.com/mengzhuo/zerorpc.(*socket).listen(0xc208185600)
        /home/meng/projects/PQServer/goedge/src/github.com/mengzhuo/zerorpc/socket.go:121 +0x78 fp=0xc2080b3fd8 sp=0xc2080b3e60
runtime.goexit()
        /home/meng/projects/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc2080b3fe0 sp=0xc2080b3fd8
created by github.com/mengzhuo/zerorpc.connect
        /home/meng/projects/PQServer/goedge/src/github.com/mengzhuo/zerorpc/socket.go:41 +0x2ff

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080c6680, 0x72, 0x0, 0x0)
        /home/meng/projects/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080c6680, 0x0, 0x0)
        /home/meng/projects/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080c6620, 0x0, 0x7ffbcfd94e60, 0xc208079678)
        /home/meng/projects/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc2080440f8, 0xc2080b3e50, 0x0, 0x0)
        /home/meng/projects/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc2080440f8, 0x0, 0x0, 0x0, 0x0)
        /home/meng/projects/go/src/net/tcpsock_posix.go:244 +0x4c
goroutine 184 [sleep]:
github.com/mengzhuo/zerorpc.(*channel).sendHeartbeats(0xc2080c6540)
        /home/meng/projects/PQServer/goedge/src/github.com/mengzhuo/zerorpc/channel.go:132 +0x35
created by github.com/mengzhuo/zerorpc.(*channel).sendEvent
        /home/meng/projects/PQServer/goedge/src/github.com/mengzhuo/zerorpc/channel.go:104 +0x318

rax     0x0
rbx     0x02015/06/29 23:10:22 ZeroRPC socket created new channel

rcx     0xffffffffffffffff2015/06/29 23:10:22 Channel 3414f9f7-a197-4941-7482-945bb0582840 sending event 3414f9f7-a197-4941-7482-945bb0582840

rdx     0x6
rdi     0x6e22
2015/06/29 23:10:22 ZeroRPC socket sent event 3414f9f7-a197-4941-7482-945bb0582840
rsi     0x6e3f
rbp     0x1
rsp     2015/06/29 23:10:22 ZeroRPC socket sent 99 bytes
2015/06/29 23:10:22 ZeroRPC socket listening for incoming data
2015/06/29 23:10:22 ZeroRPC socket received 129 bytes
2015/06/29 23:10:22 ZeroRPC socket recieved event 4bf2cc48-7d6e-4066-b57b-57cbb11c9948
2015/06/29 23:10:22 ZeroRPC socket routing event 4bf2cc48-7d6e-4066-b57b-57cbb11c9948 to channel 21435e0f-0e1b-48cb-55a3-e4449f16dfb1
0x7ffb9b7fdbb8
r8      0x7ffb9b7fe700
r9      0xe2
r10     0x8
r11     0x206
r12     0xffffffff
r13     0xffffffff
r14     0x0
r15     0x7ffb9c015f40
rip     0x7ffbcf34ccc9
rflags  0x206
cs      0x33
fs      0x0
gs      0x0
exit status 2
```

**Comment by pebbe** [comment]
Are you accessing sockets from more than one goroutine?

**Comment by mengzhuo** [comment]
Yes, you are right.
But I only reuse those clients after other zerorpc client finish their request / Invoke.

```
type RPC struct {
    Endpoint string
    Limit    int
    Buffer   chan *zerorpc.Client
}

func NewRPC(endpoint string, limit int) *RPC {
    return &RPC{endpoint, limit, make(chan *zerorpc.Client, limit)}
}

func (r *RPC) Get() (*zerorpc.Client, error) {

    select {
    case c := <-r.Buffer:
        return c, nil
    default:
        glog.V(2).Infof("New RPC client of %s", r.Endpoint)
        return zerorpc.NewClient(r.Endpoint)
    }

}

func (r *RPC) Put(c *zerorpc.Client) {
    defer func() {
        if r := recover(); r != nil {
            glog.Errorf("Put client failed:%s", r)
        }
    }()
    select {
    case r.Buffer <- c:
    default:
        c.Close()
    }
```

**Comment by pebbe** [comment]
Try not using sockets from more than one goroutine, see if the problem disappears.

**Comment by mengzhuo** [comment]
It disappeared after I don't invoke client.Close() manually.
Let the GC do the job :)
